---
- name: Converge
  hosts: all
  become: true

  vars:
    ufw_reset: false

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - weareinteractive.ufw
